### ISSUE TITLE
appendToStream with a large number of events

### ISSUE THREAD

**Issue by MarshallRJ** [nicdex/eventstore-node#27]
When appending a large number of events  to a stream. 

[Pull request with an append to stream test](https://github.com/nicdex/eventstore-node/pull/26)

The connection retry limit is exceeded:

_Error: Expected 2 assertions, 0 ran
    at done (/mnt/c/projects/rjmarshall/eventstore-node/node_modules/nodeunit/lib/types.js:121:25)
    at /mnt/c/projects/rjmarshall/eventstore-node/node_modules/nodeunit/lib/core.js:219:25
    at /mnt/c/projects/rjmarshall/eventstore-node/node_modules/nodeunit/deps/async.js:168:13
    at /mnt/c/projects/rjmarshall/eventstore-node/node_modules/nodeunit/deps/async.js:131:25
    at /mnt/c/projects/rjmarshall/eventstore-node/node_modules/nodeunit/deps/async.js:165:17
    at /mnt/c/projects/rjmarshall/eventstore-node/node_modules/nodeunit/deps/async.js:463:34
    at EventStoreNodeConnection.<anonymous> (/mnt/c/projects/rjmarshall/eventstore-node/test/common/base_test.js:48:5)
    at emitOne (events.js:101:20)
    at EventStoreNodeConnection.emit (events.js:189:7)
    at EventStoreConnectionLogicHandler.<anonymous> (/mnt/c/projects/rjmarshall/eventstore-node/src/eventStoreNodeConnection.js:57:10)
    at emitOne (events.js:96:13)
    at EventStoreConnectionLogicHandler.emit (events.js:189:7)
    at EventStoreConnectionLogicHandler._closeConnection (/mnt/c/projects/rjmarshall/eventstore-node/src/core/eventStoreConnectionLogicHandler.js:188:8)
    at /mnt/c/projects/rjmarshall/eventstore-node/src/core/eventStoreConnectionLogicHandler.js:66:10
    at Immediate._handlers.(anonymous function) (/mnt/c/projects/rjmarshall/eventstore-node/src/core/simpleQueuedHandler.js:19:7)
    at runCallback (timers.js:653:20)

Error: Retry limit reached. Operation: Operation AppendToStreamOperation (dba851f9-721e-4f70-a3fe-29616a70b705): Stream: test-0c952655-8ee4-4bea-9db7-b63f16582676, ExpectedVersion: -2, retry count: 10, created: 08:09:27.525, last updated: 08:09:53.444, RetryCount: 10
    at OperationsManager.scheduleOperationRetry (/mnt/c/projects/rjmarshall/eventstore-node/src/core/operationsManager.js:120:30)
    at /mnt/c/projects/rjmarshall/eventstore-node/src/core/operationsManager.js:86:10
    at Array.forEach (native)
    at OperationsManager.checkTimeoutsAndRetry (/mnt/c/projects/rjmarshall/eventstore-node/src/core/operationsManager.js:85:19)
    at EventStoreConnectionLogicHandler._timerTick (/mnt/c/projects/rjmarshall/eventstore-node/src/core/eventStoreConnectionLogicHandler.js:614:26)
    at /mnt/c/projects/rjmarshall/eventstore-node/src/core/eventStoreConnectionLogicHandler.js:96:10
    at Immediate._handlers.(anonymous function) (/mnt/c/projects/rjmarshall/eventstore-node/src/core/simpleQueuedHandler.js:19:7)
    at runCallback (timers.js:653:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers_.js:596:5)

**Comment by nicdex** [comment]
I have identified the issue, I will this over the weekend.

**Comment by nicdex** [comment]
Fixed in package 0.0.30.

Sending should now work with a large number of events. That being said it is not optimal to send a large number of events in one append. You should batch your append.
