### ISSUE TITLE
ReferenceError on connection drop

### ISSUE THREAD

**Issue by nicdex** [nicdex/eventstore-node#9]
ERROR:  ReferenceError: connectionId is not defined
    at /home/nicolas/dev/adaptech/sturgeon/node_modules/eventstore-node/lib/dist.js:3111:69
    at Hash.forEach (/home/nicolas/dev/adaptech/sturgeon/node_modules/eventstore-node/lib/dist.js:3046:6)
    at SubscriptionsManager.purgeSubscribedAndDroppedSubscriptions (/home/nicolas/dev/adaptech/sturgeon/node_modules/eventstore-node/lib/dist.js:3110:30)
    at EventStoreConnectionLogicHandler._tcpConnectionClosed (/home/nicolas/dev/adaptech/sturgeon/node_modules/eventstore-node/lib/dist.js:1913:24)
    at /home/nicolas/dev/adaptech/sturgeon/node_modules/eventstore-node/lib/dist.js:1565:11
    at Immediate._handlers.(anonymous function) (/home/nicolas/dev/adaptech/sturgeon/node_modules/eventstore-node/lib/dist.js:2176:8)
    at Immediate.immediate._onImmediate (timers.js:435:18)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by nicdex** [comment]
fixed in 0.0.9
